apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: sungweb
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        run: sungweb 
    spec:
      containers:
      - image: gcr.io/sunarai-1350/sungweb:af50fafca54639af864f2e691a83a7e34fe910b66b35ffce79acc62651793a1a
        name: sungweb
        volumeMounts:
        - name: sungstorage
          mountPath: /var/www/html/sungweb
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: sungstorage
        persistentVolumeClaim:
          claimName: sungstorage-pvc
